### ISSUE TITLE
ESP32-Code.ino - Compile error: invalid conversion from 'int' to 'i2s_bits_per_sample_t' [-fpermissive]

### ISSUE THREAD

**Issue by kaloprojects** [justin23456543/ESP32-Voice-Assistant-with-Speech-to-Text-Perplexity-AI-and-Text-to-Speech#2]
Hi Justin, a more simple question ;) .. today i tried to use parts of your your _.ino to implement recording audio to SD card_ , but struggling on a simple issue, as i always get same compile error in you .ino script, do you have any idea ? Asking you as i spent hours today and didn't get solved ;)

The line ' .mode = (i2s_mode_t)(I2S_MODE_MASTER | I2S_MODE_RX),' seems not working .. the cast (i2s_mode_t) fails.

Seems a well know issue (data type enum), see here: https://github.com/espressif/arduino-esp32/issues/631
I also tried the the mentioned idea with 'static_cast<i2s_mode_t> .. ' but doesn't work either
Do you have any idea (or work around?) .. does it work in your Arduino compiler ?
(fyi: just updated to latest Espressif ESP32 library 2.0.16, same error)

see screenshot:

**Comment by kaloprojects** [comment]
![Error](https://github.com/justin23456543/ESP32-Based-Voice-Assistant-with-Perplexity-AI/assets/61752606/1072340d-dd72-4430-a2f3-ac7378c3cceb)

Thanks for your time ! :)

**Comment by kaloprojects** [comment]
solved, funny .. i would have read the error message exactly, _your cast on .mode was correct,!_ it was just missed one additional cast ;). _this has to be added to your code (yellow):_

![Screenshot](https://github.com/justin23456543/ESP32-Based-Voice-Assistant-with-Perplexity-AI/assets/61752606/9c90cb42-89a0-4cf1-abc7-c7a11af72bec)

**Comment by kaloprojects** [comment]
SOLVED,

so now i can connect some wire (adding SD card reader) .. and start testing your recording code  ;)

**Comment by kalodj** [comment]
one (cast) was mised in .ino code, line:
.bits_per_sample = (i2s_bits_per_sample_t) BITS_PER_SAMPLE,
